spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 1000
      initial-size: 100
      max-wait: 60000
      min-idle: 500
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

  rabbitmq:
    host: 119.23.249.44
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# https://docs.spring.io/spring-boot/docs/2.5.2/reference/html/application-properties.html#application-properties
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10

        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true

        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0



  #static
  web:
    resources:
      add-mappings: true
      cache:
        period: 3600
      chain:
        cache: true
        enabled: true
        compressed: true
      static-locations: classpath:/static/

#  resources:
#    add-mappings: true
#    cache:
#      period: 3600
#    chain:
#      cache: true
#      enabled: true
#      html-application-cache: true
#      compressed: true
#    static-locations: classpath:/static/

#  redis:
#    host: r-2vcf0y52ujylpgriqfpd.redis.cn-chengdu.rds.aliyuncs.com
#    port: 6379
#    password: lfk:Liu123456
#    client-type: jedis
#    connect-timeout: 3000
#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        max-wait: 3000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pica.miaosha.domian
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000


